<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        {% block base %}
        <base href="{{ basepath }}"/>
        {% endblock %}
        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <link rel="stylesheet" type="text/css" href="assets/lib/bootstrap-4.0.0-alpha.6-dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="assets/lib/slick/slick.css"/>
        <link rel="stylesheet" type="text/css" href="assets/lib/slick/slick-theme.css"/>
        <link rel="stylesheet" href="assets/css/style.css"/>

        <title>
            {% block title %}
            IntraSAIN
            {% endblock %}
        </title>

    </head>

    <body>
        {% block header %}
        <header class="margin-0 align-items-center d-flex justify-content-between">
            <div id="brand">
                <a href="home">
                    <svg class="d-inline-block align-top" id="Layer_1" xmlns="http://www.w3.org/2000/svg" width="54" height="41" viewBox="0 0 241 181" class="undefined">
                        <path d="M142 143.9c-21-10.8-37.3-23.4-50-38.6C77.3 87.6 67.2 69.3 61.8 50.8c-0.5-1.7-1.2-4.4-1.8-7.3C52.5 53.3 47.6 64.4 45.4 75.9c4.3 19.3 18 37.8 38.2 44.7l-10.2 30.4c27.3 21.4 65.6 21.7 93.2 0.8 -0.4 0-0.7-0.1-1.1-0.1C158.5 150.7 149 147.5 142 143.9z"/>
                        <path d="M83.6 37c6.5 28 31.8 61 60 78.5 9.3 5.8 24 12.5 34.8 12.5 3.2 0 5.8-0.6 7.7-1.8l3.1-1.9c3-6.1 5.2-12.6 6.4-19.1 -4.3-19.3-18-37.8-38.2-44.7l10.2-30.4c-23.6-18.6-55.7-21.2-81.7-8l-0.1 0.1C83.5 25.5 82.6 33.1 83.6 37z"/>
                        <path d="M67.5 16c0.7-0.3 1.2-0.5 1.6-0.6C25.1 27.4-0.3 74.3 1.7 105.4c2 31.8 22.6 58.1 48.1 73.3l15.5-46.2c-28.1-16.8-42.2-58.9-28.3-87.6C44.3 27.6 61.2 18.4 67.5 16z"/>
                        <path d="M239.3 75.6c-2-31.8-22.6-58.1-48.1-73.3l-15.5 46.3c28.1 16.8 42.2 58.9 28.4 87.6 -7.4 17.2-24.2 26.4-30.6 28.9 -0.7 0.3-1.3 0.5-1.7 0.6C215.9 153.6 241.3 106.7 239.3 75.6z"/>
                    </svg>
                    <nav class="navbar-brand opensans hidden-md-down">IntraSAIN</nav>
                </a>
            </div>
            <div id="header_menu" class="hidden-lg-down"> 
                <a href="/">Página Principal</a>
                <a href="#">Áreas da SAIN</a>
                <a href="#">Sain na Internet</a>
                <a href="#">Ferramentas</a>
                <a href="#">Legislação</a>
            </div>
            <form id="header_search">
                <div class="form-group padding-0 margin-0">
                    <input type="search"/>
                    <input type="submit" value=""/>
                </div>
            </form>
            <div class="d-flex" id="header_user">
                <div class="float-left text-right hidden-lg-down">
                    <div>{{ usuario.nome_preferido }}</div>
                    <div><small>{{ usuario.coordenacao }}</small></div>
                </div>
                <div class="float-right">
                    <img class="avatar" src="assets/image/avatar-default.png" />
                </div>
            </div>

        </header>
        {% endblock %}

        <main>
            {% block content%}
            {% endblock%}
        </main>


        <footer>
            {% block footer%}
            <div class="container">
                <div class="row row-width-fix">
                    <div class="col footer-text">
                        <p class="footer-title">SAIN SEDE</p>
                        <p>Esplanada dos Ministérios</p>
                        <p>Bloco P - 2º Andar</p>
                        <p>Sala 223</p>
                        <p>Brasília/DF - 70048-900</p>
                        <p>(61) 3412-2290/2227</p>
                    </div>
                    <div class="col footer-text">
                        <p class="footer-title">SAIN ASA SUL</p>
                        <p>SAS Quadra 3 Bloco O</p>
                        <p>10º Andar</p>
                        <p>Ed. Órgãos Regionais/MF</p>
                        <p>Brasília/DF - 70079-900</p>
                        <p>(61) 3412-4014/4077</p>
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <span>&copy; 2017 Secretaria de Assuntos Internacionais - Ministério da Fazenda</span>
                </div>
            </div>
            {% endblock %}
        </footer>

        <script src="assets/lib/jquery/jquery-3.2.0.min.js"></script>
        <script src="assets/lib/tether/js/tether.min.js"></script>
        <script src="assets/lib/bootstrap-4.0.0-alpha.6-dist/js/bootstrap.min.js"></script>

        {% block scripts %}
        
        {% endblock %}

    </body>
</html>