{% extends "base.phtml" %}

{% block title %}
    {{ noticia.titulo }} - IntraSAIN
{% endblock %}

{% block content %}
    <section class="container">
        <div class="d-lg-flex flex-column">
            <nav id="breadcrumb">
                <span>Você está em:</span>
                <ol>
                    <li><a href="home">Home</a></li>
                    <li><a href="{{ noticia.url_unidade }}">{{ noticia.unidade }}</a></li>
                    <li><a href="home">{{ noticia.url_colecao }}</a></li>
                    <li>{{ noticia.titulo }}</li>
                </ol>
            </nav>

            <div class="d-flex">
                <section id="noticia_corpo" class="">
                    <section id="noticia_header">
                        <div class="margin-0 padding-0 border-bottom-exthin-light">
                            <h1>{{noticia.titulo}}</h1>
                            <small>{{noticia.metadados}}</small>
                        </div>
                    </section>
                    <article>
                        {{ noticia.conteudo }}
                    </article>
                    <section id="noticia_footer">
                        TODO: footer pra notícias (incluir coisas como notícias relacionadas, talvez. Também talvez incluir uns items de navegação, como links pra notícia anterior e próxima. Também talvez uns botões como "copiar link para esta página". Tava olhando também alguma biblioteca de text-to-speech. Aí eu colocaria um botão ou aqui ou no topo da página.
                    </section>
                </section>

                <aside id="menu_lateral">
                    <section>
                        <h2 class="text-right">{{ noticia.unidade }}</h2>
                        <ul class="list-group">
                            {% for link in menu_unidade %}
                                <li class="list-group-item"><a href="{{ link.url }}">{{ link.descricao }}</a></li>
                                {% endfor %}
                        </ul>
                    </section>

                    <h2 class="text-right">Notícias Anteriores</h2>
                    <ul class="list-group">
                        {% for link in noticias_anteriores %}
                            <li class="list-group-item">
                                <a href="{{ link.url_ref }}">{{ link.descricao }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </aside>
            </div> 
        </div>
    </section>
{% endblock %}