<?php

namespace App\Models;

use App\Models\Interfaces\UrlInterface;
use App\Models\Scopes\AtivoScope;
use Illuminate\Database\Eloquent\Model;

class Objeto extends Model implements UrlInterface
{

    protected static function boot()
    {
        static::addGlobalScope(new AtivoScope());
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function scopeTipo($query, $tipo)
    {
        return static::where('objeto_tipo_id', ObjetoTipo::idOf($tipo));
    }


    public function scopeUrl($query)
    {
        $created_at = $this->created_at;

        return 'storage/' . $created_at->format('Y/m/') . $this->filename;
    }
}
