<?php

namespace App\Models;

use App\Models\Scopes\AtivoScope;
use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        self::addGlobalScope(new AtivoScope());
        parent::boot(); // TODO: Change the autogenerated stub
    }

    protected $dates = ['last_access'];

    public function rh_dados()
    {
        return $this->hasOne(RhDado::class, 'usuario_id', 'id');
    }
}
