<?php

namespace App\Models;

use App\Models\Scopes\AtivoScope;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Usuario extends Authenticatable
{
    use Notifiable;

    protected $hidden = [
        'remember_token', 'password',
    ];

    protected $fillable = [
        'nome_completo', 'nome_curto', 'cpf', 'password',
    ];



    protected static function boot()
    {
        self::addGlobalScope(new AtivoScope());
        parent::boot(); // TODO: Change the autogenerated stub
    }

    protected $dates = ['last_access'];

    public function rh()
    {
        return $this->hasOne(UsuarioRH::class, 'usuario_id', 'id');
    }
}
